# playbook.yml

- name: Install Jenkins and CloudWatch Agent
  hosts: jenkins_servers
  become: yes
  tasks:
    - name: Install Jenkins
      apt:
        name: openjdk-11-jdk jenkins
        state: present

    - name: Install CloudWatch Agent
      apt:
        name: cloudwatch-agent
        state: present
